# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000


development:
  <<: *default
  database: ncn_reporting_development
  host: localhost
  pool: 5
  username: msdev
  password: password
  #### heroku pg:backups capture --app ncn-reporting
  #### sudo -u postgres psql
  #### pg_restore --verbose --clean --no-acl --no-owner -h localhost -U msdev -W -d ncn_reporting_development ~/cjreeve/Sustrans/ncn-reporting-backup-2015.10.17.dump
  # database: db/development.sqlite3

test:
  <<: *default
  database: ncnreporting_2016_09_11_test
  host: localhost
  username: msdev
  password: password

production:
  <<: *default
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
